create table Book ( Bno int, Name char(20), Author char(10), Price float, primary key(Bno));
create table student ( StuID int unique, Name char(10) , primary key (StuID));
insert into Book values ( 11, 'Database', 'Korth', 49.1);
insert into Book values( 12, 'Algorithm', 'Milie',23.2);
insert into Book values( 13, 'Algorithm', 'Ben',77.4);
insert into Book values ( 14,'English','Jane',33.3);
insert into Book values ( 15, 'Software', 'Ismaille', 88.9 );
insert into Book values ( 16,'Calculus','Ben',33.3);
insert into student values ( 1, 'Jerry');
insert into student values ( 2, 'Tom');
insert into student values ( 3, 'Susan');
insert into student values( 4,'Jack');
insert into student values( 5,'Robin');
insert into  student values( 6,'Alice');
insert into student values( 7,'Tom');
select * from Book where Bno = 11;
select * from Book where Bno <> 11;
select * from Book where Price <= 49.1;
select * from Book where Price < 49.1;
select * from Book where Price >= 33.3;
select * from Book where Price > 33.3;
select * from Book where Price = 33.3 and Name = 'English';
select * from student where Name = 'Tom';
select * from student where Name = 'Tom' and StuID = 2;
delete from student where StuID = 1;
select * from Book;
create index SID on student(StuID);
create index NAME on student (Name);
drop index SID;
drop table student;
drop table Book;
